---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 문제
      url: "/reference-known-issues.html"
  - title: 시작하십시오
    entries:
    - title: StorageGRID 시스템에 대해 알아보십시오
      url: "/task-discover-storagegrid.html"
  - title: StorageGRID 시스템 관리
    entries:
    - title: StorageGRID 시스템을 봅니다
      url: "/task-view-storagegrid.html"
    - title: StorageGRID 인증서를 보고 업데이트합니다
      url: "/task-manage-certificates.html"
    - title: 고급 보기를 사용하여 StorageGRID를 관리합니다
      url: task-administer-storagegrid.html
    - title: StorageGRID에서 NetApp 데이터 서비스 사용
      url: "/task-enable-data-services.html"
    - title: 작업 환경을 제거합니다
      url: "/task-remove-storagegrid.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
